2023_10_20/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # 회원가입
    path('signup/', views.signup, name='signup'),
    # 로그인
    path('login/', views.login, name='login'),
    # 로그아웃
    path('logout/', views.logout, name='logout'),
    # 프로필페이지
    path('profile/<username>/', views.profile, name='profile'),
    #구독 기능
    path('<int:user_pk>/follow/<int:board_pk>/', views.follow, name='follow'),
]

2023_10_20/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
    path('<int:board_pk>/likes/', views.likes, name='likes'),
]

2023_10_20/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

2023_10_20/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-warning">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
        {% if request.user.is_authenticated %}
                <form action="{% url "accounts:logout" %}" method="post">
                    {% csrf_token %}
                        <button class="nav-item btn btn-warning">로그아웃</button>
                </form>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

2023_10_20/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>Document</title>
  <style>
  body {
    background-image : url('https://images.unsplash.com/photo-1498721425774-488298864da7?auto=format&fit=crop&q=80&w=1469&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
    );
    font-weight : bolder;
  }
</style>
</head>
<body class='text-warning'>
  <div class="mt-3 container">
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>