2023_10_13/trends/urls.py
from django.urls import path
from . import views

app_name = 'trends'
urlpatterns = [
    path('keyword/', views.keyword, name='keyword'),
    path('keyword/<int:pk>/', views.delete, name='delete'),
    path('crawling/', views.crawling, name='crawling'),
    path('crawling/histogram/', views.histogram, name='crawling_histogram'),
    path('crawling/advanced/', views.acvanced, name='crawling_advanced'),
]

2023_10_13/trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.TextField()
    created_at = models.DateField(auto_now=True)

class Trend(models.Model):
    name = models.TextField()
    result = models.IntegerField()
    search_period = models.TextField()
    created_at = models.DateField(auto_now=True)

2023_10_13/trends/forms.py
from django import forms
from .models import Keyword, Trend

class KeywordForm(forms.ModelForm):
    name = forms.CharField(
        label='키워드',
        widget=forms.TextInput(
            attrs={
                'max_length': 20,
            }
        )
    )
    class Meta(Keyword):
        model = Keyword
        fields = ['name',]


class TrendForm(forms.ModelForm):
    class Meta:
        model = Trend
        fields = '__all__'

2023_10_13/trends/views.py
from django.shortcuts import render, redirect
from .models import Keyword, Trend
from .forms import KeywordForm
from selenium import webdriver
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import base64
from io import BytesIO

# Create your views here.
def keyword(request):
    if request.method == 'POST':
        form = KeywordForm(request.POST)
        if form.is_valid():
            form.save()
    keywords = Keyword.objects.all()
    form = KeywordForm()
    context = {
        'keywords': keywords,
        'form': form
    }
    return render(request, 'trends/keyword.html', context)

def delete(request, pk):
    keyword = Keyword.objects.get(pk=pk)
    keyword.delete()
    return redirect('trends:keyword')

def crawling(request):
    def get_google_data(keywords):
        # 가져올 웹 페이지 url
        url = f'https://www.google.com/search?q={keywords}'

        driver = webdriver.Chrome()
        driver.get(url)

        # 열린 페이지 소스를 받아옴
        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        # 검색 결과 가져오기
        # div 태그 안의 id 가 result-stats 라는 요소
        result_stats = soup.select_one("div#result-stats")
        # print(result_stats.text)
        temp = result_stats.text[7:-10].replace(',','')
        return int(temp)
    
    keywords = Keyword.objects.all()
    for keyword in keywords:
        result = get_google_data( keyword.name)
        trend, is_created = Trend.objects.get_or_create(defaults={'result': result},name=keyword.name, search_period='all')
        if is_created:
            trend.result = result
        trend.save()
    trends = Trend.objects.all()
    context = {
        'trends': trends,
    }
    return render(request, 'trends/crawling.html', context)
    

def histogram(request):
    x = []
    y = []
    trends = Trend.objects.all()
    for trend in trends:
        if trend.search_period == 'all':
            x.append(trend.name)
            y.append(trend.result)

    plt.clf()
    plt.bar(range(0, len(x)), y, label='Trends')
    plt.xticks(range(0, len(x)), x, rotation=45)
    plt.grid()
    plt.title('Technology Trend Analysis')
    plt.xlabel('keyword')
    plt.ylabel('result')
    plt.legend()
    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'chart_image': f'data:image/png;base64,{image_base64}'
    }
    return render(request, 'trends/crawling_histogram.html', context)

def acvanced(request):
    def get_google_data(keywords):
        # 가져올 웹 페이지 url
        url = f'https://www.google.com/search?q={keywords}&tbs=qdr:y'

        driver = webdriver.Chrome()
        driver.get(url)

        # 열린 페이지 소스를 받아옴
        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        # 검색 결과 가져오기
        # div 태그 안의 id 가 result-stats 라는 요소
        result_stats = soup.select_one("div#result-stats")
        # print(result_stats.text)
        temp = result_stats.text[7:-10].replace(',','')
        return int(temp)
    
    x = []
    y = []
    
    keywords = Keyword.objects.all()
    for keyword in keywords:
        result = get_google_data(keyword.name)
        trend, is_created = Trend.objects.get_or_create(defaults={'result': result},name=keyword.name, search_period='year')
        if is_created:
            trend.result = result    
        trend.save()
        x.append(trend.name)
        y.append(trend.result)

    plt.clf()
    plt.bar(range(0, len(x)), y, label='Trends')
    plt.xticks(range(0, len(x)), x, rotation=45)
    plt.grid()
    plt.title('Technology Trend Analysis')
    plt.xlabel('keyword')
    plt.ylabel('result')
    plt.legend()
    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'chart_image': f'data:image/png;base64,{image_base64}'
    }
    return render(request, 'trends/crawling_advanced.html', context)

2023_10_13/trends/templates/trends/crawling.html
{% extends "base.html" %}

{% block content %}
    <h1>크롤링 기초 - 전체 기간 검색 결과</h1>
    <br>
    {% for trend in trends %}
        {% if trend.search_period == 'all' %}
        <h3>검색 결과: {{trend.name}} - {{trend.result}}개 / 검색일자: {{trend.created_at}}</h3>
        <hr>
        {% endif %}
    {% endfor %}    
{% endblock content %}

2023_10_13/trends/templates/trends/crawling_advanced.html
{% extends "base.html" %}

{% block content %}
    <h2>지난 1년 간의 트렌드</h2>
    <img src="{{chart_image}}" alt="">
{% endblock content %}

2023_10_13/trends/templates/trends/crawling_histogram.html
{% extends "base.html" %}

{% block content %}
<h2>출력 결과 히스토그램</h2>
<img src="{{chart_image}}" alt="">
{% endblock content %}

2023_10_13/trends/templates/trends/keyword.html
{% extends "base.html" %}
{% block content %}
    <h1>키워드 추가</h1>
    <form action="{% url "trends:keyword" %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="생성하기">
    </form>
    <hr>
    <h2>분석을 원하는 키워드 목록</h2>
    {% for keyword in keywords %}
        <p>{{keyword.pk}}번째 키워드 - {{keyword.name}}</p>
        <form action="{% url "trends:delete" keyword.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제하기">
        </form>
        <hr>
    {% endfor %}
    
{% endblock content %}